// <auto-generated />
using System;
using MagicVillaAPI.Modelos.DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250320141437_UpdateNumeroVilla")]
    partial class UpdateNumeroVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVillaAPI.Modelos.NumeroVilla", b =>
                {
                    b.Property<int>("VillaNO")
                        .HasColumnType("int");

                    b.Property<string>("DetalleEspecial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNO");

                    b.HasIndex("VillaId");

                    b.ToTable("NumeroVillas");
                });

            modelBuilder.Entity("MagicVillaAPI.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MetrosCuadrados")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "amenidad 1",
                            Detalle = "Detalle Villa",
                            FechaActualizacion = new DateTime(2025, 3, 20, 11, 14, 37, 40, DateTimeKind.Local).AddTicks(3759),
                            FechaCreacion = new DateTime(2025, 3, 20, 11, 14, 37, 40, DateTimeKind.Local).AddTicks(3714),
                            ImagenUrl = "",
                            MetrosCuadrados = 50.0,
                            Nombre = "Villa Limache",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "Amenidad 2",
                            Detalle = "Detalle Villa",
                            FechaActualizacion = new DateTime(2025, 3, 20, 11, 14, 37, 40, DateTimeKind.Local).AddTicks(3768),
                            FechaCreacion = new DateTime(2025, 3, 20, 11, 14, 37, 40, DateTimeKind.Local).AddTicks(3765),
                            ImagenUrl = "",
                            MetrosCuadrados = 200.0,
                            Nombre = "Villa Quilpue",
                            Ocupantes = 6,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 3,
                            Amenidad = "Amenidad 3",
                            Detalle = "Detalle Villa",
                            FechaActualizacion = new DateTime(2025, 3, 20, 11, 14, 37, 40, DateTimeKind.Local).AddTicks(3775),
                            FechaCreacion = new DateTime(2025, 3, 20, 11, 14, 37, 40, DateTimeKind.Local).AddTicks(3772),
                            ImagenUrl = "",
                            MetrosCuadrados = 300.0,
                            Nombre = "Villa VillaAlemana",
                            Ocupantes = 8,
                            Tarifa = 300.0
                        });
                });

            modelBuilder.Entity("MagicVillaAPI.Modelos.NumeroVilla", b =>
                {
                    b.HasOne("MagicVillaAPI.Modelos.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
